### ISSUE TITLE
PUBLIC_URL with Path Redirects to Base URL

### ISSUE THREAD

**Issue by jburgess** [imagineapi/imagineapi#10]
First, thank you for making this open source. Really good stuff!

It looks like setting `PUBLIC_URL` with a path:
```
http://mj.yellow-lemon.ts.net:8055/imagineapi
```
isn't respected by the API service as the redirect to the base URL. 

Is there a workaroung?

**Comment by hgezim** [comment]
> First, thank you for making this open source. Really good stuff!

😆

Yeah, adding a path won't work. Work around is nasty (involves rewriting paths with some kind of load balancer like AWS CloudFront).
