### ISSUE TITLE
"Add a a webhook url" option not visible 

### ISSUE THREAD

**Issue by jigneshk5** [imagineapi/imagineapi#11]
Hi,
I hosted the imagineAPI in my server But There is no option to add webhook url in my user's setting page. 
Please check attached image:
![image](https://github.com/imagineapi/imagineapi/assets/36167650/fcd393ec-39cf-4d39-ae26-e206dfe421bb)

Please help me find the option to add webhook url.

**Comment by hgezim** [comment]
Hey, added webhooks to self hosted. Try upgrade: https://docs.imagineapi.dev/self-host-install/upgrade
