### ISSUE TITLE
Getting this error message `dependency failed to start: container imagineapi-rabbitmq-1 is unhealthy`

### ISSUE THREAD

**Issue by backermanbd** [imagineapi/imagineapi#13]
I'm selfhosting on my local device, Manjaro. 

When I run the docker command, I'm getting his error:
```
dependency failed to start: container imagineapi-rabbitmq-1 is unhealthy
```

How to fix this?

**Comment by andres-ortizl** [comment]
I managed to solve this by upgrading the the rabbitmq docker image up to rabbitmq:3.10.0-management. 
This is defined in the docker-compose.yml file.

**Comment by hgezim** [comment]
Actually this is funny. It happens randomly sometimes. Just need to run `docker compose up -d` again, usually.

I think it's some kind of log file permission not existing the first time around. Not 100% sure.
