### ISSUE TITLE
Never ending starting

### ISSUE THREAD

**Issue by abrvham** [imagineapi/imagineapi#16]
Hello, I have set-up the tool on AWS EC2 Ubuntu.
The problem is the bot status stays on "Starting" undefinitely.
Here are the logs:
`bot_1       | 2024-01-15 22:41:02 info: authentication: ✨ loginScreen global pool:  {
bot_1       |   "service": "consumer",
bot_1       |   "discord_email": "xxxx",
bot_1       |   "instance": "xxxx"
bot_1       | }
bot_1       | browser-actions.ts line:236 jsonResponse undefined
bot_1       | 2024-01-15 22:41:18 error: Browser agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 {
bot_1       |   "service": "consumer",
bot_1       |   "discord_email": "xxxx",
bot_1       |   "instance": "xxxx"
bot_1       | }
bot_1       | 2024-01-15 22:41:19 error: loginScreen. Saving screenshot to /usr/src/app/logs/login-screen-1705358479646-y-X8eEHeQgfcoAXuaFh5a.png {
bot_1       |   "service": "consumer",
bot_1       |   "discord_email": "xxxx",
bot_1       |   "instance": "xxxx"
bot_1       | }
bot_1       | 2024-01-15 22:41:20 info: authentication: ✨ captchaLoaded global pool:  {
bot_1       |   "service": "consumer",
bot_1       |   "discord_email": "xxxx",
bot_1       |   "instance": "xxxx"
bot_1       | }
`

Do you have any hint of what is the cause of this issue?

Regards

**Comment by andres-ortizl** [comment]
If you download this screenshot you may be able to see the error : 

`error: loginScreen. Saving screenshot to /usr/src/app/logs/login-screen-1705358479646-y-X8eEHeQgfcoAXuaFh5a.png`

**Comment by srini-fp** [comment]
@andres-ortizl  I am having similar issue. Here is error image , How should I move forward.
![error](https://github.com/imagineapi/imagineapi/assets/129972596/9f487e6f-0b6e-49a4-b393-3f6288a43bf5)
