### ISSUE TITLE
Error trying to log into discord

### ISSUE THREAD

**Issue by andres-ortizl** [imagineapi/imagineapi#17]
Hello there I'm facing this error when the headless browser is trying to log into discord 

<img width="715" alt="image" src="https://github.com/imagineapi/imagineapi/assets/16100350/edc7bc5a-8d67-4e7a-a3c9-8f44209648f8">

Seems like it can't bypass this captcha somehow.
 I've verified that my 2captcha works just fine.

Thank you !

**Comment by michaelaball** [comment]
same issue here

**Comment by michaelaball** [comment]
you can bypass it if you have logged into discord from the same IP already

**Comment by Nzenou** [comment]
same issue

**Comment by Nzenou** [comment]
browser-actions.ts line:236 jsonResponse undefined
bot-1  | 2024-01-17 21:52:41 error: Browser agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 {
bot-1  |   "service": "consumer",
bot-1  |   "discord_email": "nathannzenou@gmail.com",
bot-1  |   "instance": "157f2dbbf22f051b427acf2865a8481b"
bot-1  | }
bot-1  | 2024-01-17 21:52:43 error: loginScreen. Saving screenshot to /usr/src/app/logs/login-screen-1705528363722-LORY6WszoDoDuCbfRA7Yn.png {
bot-1  |   "service": "consumer",
bot-1  |   "discord_email": "nathannzenou@gmail.com",
bot-1  |   "instance": "157f2dbbf22f051b427acf2865a8481b"
bot-1  | }

![login-screen-1705526224411-oC-MFtba0QOiWghlIeFjA](https://github.com/imagineapi/imagineapi/assets/44473759/8fb88756-8f00-4141-b04f-0a40e52c5e26)
