### ISSUE TITLE
is this normal

### ISSUE THREAD

**Issue by wuxx97** [imagineapi/imagineapi#24]
After following the tutorial operation, display,
![image](https://github.com/imagineapi/imagineapi/assets/58180590/08535791-6ad3-45f5-9dd2-8037f158bc34)
![image](https://github.com/imagineapi/imagineapi/assets/58180590/7fb72e92-a5e7-4cf1-9897-2eac572c233d)
I have not paid for my discord midjourney bot. Is this normal

**Comment by limcolin** [comment]
Follow the instructions starting from here:
https://docs.imagineapi.dev/self-host-install/ImagineAPI#verify-discord-login-link

You need to log into your RabbitMQ dashboard and paste the link from discord

**Comment by wuxx97** [comment]
thank u!I solved this problem a few days ago



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Colin ***@***.***&gt;; 
发送时间: 2024年2月20日(星期二) 下午3:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imagineapi/imagineapi] is this normal (Issue #24)






从这里开始按照说明操作：
https://docs.imagineapi.dev/self-host-install/ImagineAPI验证不一致的登录链接

您需要登录到您的RabbitMQ仪表板并从discord粘贴链接

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:< Imagine api ***@***.***和&gt;
