### ISSUE TITLE
Bot Stuck on Login Screen

### ISSUE THREAD

**Issue by jamcalli** [imagineapi/imagineapi#25]
Worked for the past few weeks. Now I receive a screenshot of the login page in the logs folder, and there was an error:

```
2024-02-06 04:30:10 error: loginScreen. Saving screenshot to /usr/src/app/logs/login-screen-1707193810688-MFdE836TA4yZQpTGcfPfk.png {
  "service": "consumer",
  "discord_email": "xxxxxxx",
  "instance": "cb9e2b7a784301912abc8ba665bab99d"
```

2Auth is disabled. Password and username are correct. I do not see the 'Status' tab, but rather it shows 'Linked Midjourney Account', which is blank. It was working... Any suggestions?

**Comment by jigneshk5** [comment]
@jamcalli You found any solution, I'm also facing issue

**Comment by FABIOHIPOLITO** [comment]
You found any solution, I'm also facing issue

**Comment by jamespapapa** [comment]
@jamcalli hi there. did you solve above issue? I just have faced the same!

**Comment by aChase55** [comment]
I ran into this as well, my instance ran out of memory, I had to clean up docker with `sudo docker system prune -af` and then did a new compose up and it started working again

**Comment by hgezim** [comment]
Look at the saved screenshot. It's encountering something odd there.

**Comment by hgezim** [comment]
Glad you got it solved!

that’s an odd one for sure
