### ISSUE TITLE
White screen when starting the panel

### ISSUE THREAD

**Issue by luucav** [imagineapi/imagineapi#26]
I did the entire installation, docker above version 23, Ubuntu 22.04 (LTS) x64 Droplet on DigitalOcean with 2 GB Memory RAM.

I cloned github, set the credentials, and ran docker, the containers are even working as shown in the print below
![image](https://github.com/imagineapi/imagineapi/assets/80016546/a86dc227-db55-45b1-b0a5-87d9c3354a65)
RabbitMQ working perfectly, open panel

However, the API panel does not run
![image](https://github.com/imagineapi/imagineapi/assets/80016546/21ca660e-e385-4ddf-b4c7-4c261464f6ba)

API logs below:
`api-1  | [15:16:28.085] INFO: Loaded extensions: four-images, image
api-1  | [15:16:28.256] ERROR: Database is already installed
api-1  |     err: {
api-1  |       "type": "Error",
api-1  |       "message": "Database is already installed",
api-1  |       "stack":
api-1  |           Error: Database is already installed
api-1  |               at runSeed (/directus/node_modules/directus/dist/database/seeds/run.js:15:15)
api-1  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api-1  |               at async Command.start (/directus/node_modules/directus/dist/cli/commands/database/install.js:12:9)
api-1  |               at async Command.parseAsync (/directus/node_modules/commander/lib/command.js:935:5)
api-1  |     }
api-1  | Database already installed
api-1  | [15:16:46.280] INFO: Loaded extensions: four-images, image
api-1  | [15:16:46.289] INFO: Running migrations...
api-1  | [15:16:46.357] INFO: Database up to date
api-1  | [15:16:55.544] INFO: Loaded extensions: four-images, image
api-1  | [15:16:56.161] INFO: Snapshot applied successfully
api-1  | Creating bot user
api-1  | Bot user already exists
api-1  | Not creating standard user either
api-1  | [15:17:18.644] INFO: Loaded extensions: four-images, image
api-1  | [15:17:18.653] INFO: Running migrations...
api-1  | [15:17:18.710] INFO: Database up to date
api-1  | [15:17:30.475] INFO: Loaded extensions: four-images, image
api-1  | [15:17:30.571] WARN: PostGIS isn't installed. Geometry type support will be limited.
api-1  | [15:17:30.794] INFO: Connecting to RabbitMQ
api-1  | [15:17:30.797] INFO: Created queue "bot_status"
api-1  | [15:17:30.849] INFO: Server started at http://0.0.0.0:8055
api-1  | [15:17:30.978] INFO: Received message from queue "bot_status":
api-1  | [15:17:31.128] WARN: Update available: 9.23.1 -> 10.9.2
api-1  | [15:17:31.198] INFO: Saved bot status
api-1  | [15:17:47] GET / 302 16ms
api-1  | [15:17:47] GET /admin 304 6ms
api-1  | [15:17:47] GET /8055/admin/assets/index.23a74a40.entry.js 404 66ms
api-1  | [15:17:47] GET /8055/admin/assets/pinia.ca18f884.entry.js 404 200ms
api-1  | [15:17:47] GET /8055/admin/assets/runtime-core.esm-bundler-c59f901a.js 404 262ms
api-1  | [15:17:48] GET /8055/admin/assets/index-9ab09702.css 404 296ms
api-1  | [15:17:48] GET /8055/admin/assets/vue.runtime.esm-bundler-50cec971.js 404 299ms
api-1  | [15:17:48] GET /8055/admin/assets/vue-i18n.6dad86f2.entry.js 404 312ms
api-1  | [15:17:48] GET /8055/admin/assets/use-sync-142c55ed.js 404 267ms
api-1  | [15:17:48] GET /8055/admin/assets/vue-router.1c7a0a67.entry.js 404 121ms`

Bot logs below

`bot-1  | 2024-02-16 15:26:08 debug: Captcha not solved yet. Retrying in 5 seconds... {
bot-1  |   "service": "consumer",
bot-1  |   "discord_email": "myemail-privado",
bot-1  |   "instance": "92219359e42b22012409f5b365cf74a8"
bot-1  | }
bot-1  | 2024-02-16 15:26:13 debug: Got reponse from 2captcha: 200 {
bot-1  |   "service": "consumer",
bot-1  |   "discord_email": "myemail-privado",
bot-1  |   "instance": "92219359e42b22012409f5b365cf74a8"
bot-1  | }
bot-1  | 2024-02-16 15:26:13 debug: Captcha not solved yet. Retrying in 5 seconds... {
bot-1  |   "service": "consumer",
bot-1  |   "discord_email": "myemail-privado",
bot-1  |   "instance": "92219359e42b22012409f5b365cf74a8"
bot-1  | }
bot-1  | 2024-02-16 15:26:18 debug: Got reponse from 2captcha: 200 {
bot-1  |   "service": "consumer",
bot-1  |   "discord_email": "myemail-privado@gmail.com",
bot-1  |   "instance": "92219359e42b22012409f5b365cf74a8"
bot-1  | }
bot-1  | 2024-02-16 15:26:18 debug: Captcha not solved yet. Retrying in 5 seconds... {
bot-1  |   "service": "consumer",
bot-1  |   "discord_email": "myemail-privado@gmail.com",
bot-1  |   "instance": "92219359e42b22012409f5b365cf74a8"
bot-1  | }`

**Comment by hgezim** [comment]
`GET /8055` this looks wrong. 8055 is the port not path.
