### ISSUE TITLE
Self hosted install working well but admin

### ISSUE THREAD

**Issue by mikeydiamonds** [imagineapi/imagineapi#27]
I walked through the self-hosting tutorial and while tedious, it was well executed. Kudos.

I have a standard user account as shown in `.shared.env` but I would like admin in order to delete certain midjourney creations from the images list. Do I just need to set:

ADMIN_USER_EMAIL=me@domain.com
ADMIN_USER_PASSWORD=blahblahblah

And what happens when I redeploy? Is anything lost? Will I need to authenticate with discord again?

Thanks.

**Comment by thegje** [comment]
Hi, I have the same question, did you get an admin account working?

**Comment by mikeydiamonds** [comment]
@thegje unfortunately, I was not able to resolve. I looked in the postgres database and there is another user with email bot@example.com but the password does not match any of the keys in the .env file. I believe it has a `CONSUMER_ROLE` not the `STANDARD_ROLE`.

I even changed the email address and attempted the 'forgot password' feature but it just kicked off a discord login email.

**Comment by hgezim** [comment]
You can change the role id for the standard user (not bot@example.com) to be the admin role and get admin privileges. 

Obv. you can cause all kinds of issues with admin so careful :)
