### ISSUE TITLE
Passing in --relax returns "failed" status even though midjourney accepts successfully processes it.

### ISSUE THREAD

**Issue by cboseak** [imagineapi/imagineapi#28]
### Summary
* Passing in --relax returns "failed" status even though midjourney accepts successfully processes it.

### Example prompts that fail:
* The 2008 housing crisis, a look back  --v 6.0 --relax --ar 16:9 --no hands, letters, text, words, characters, logos, symbols, sentences
* A dog that was seen sledding in a red sled during the recent snow storm.  --v 6.0 --relax --ar 16:9 --no hands, letters, text, words, characters, logos, symbols, sentences

### Example response from API 
```
{'data': {'id': 'a5b170de-08fb-43a6-96df-7bb73a1148e8', 'prompt': 'The 2008 housing crisis, a look back  --v 6.0 --relax --ar 16:9 --no hands, letters, text, words, characters, logos, symbols, sentences', 'results': None, 'user_created': '5a08cf40-dcd0-4e39-b437-7f88a03db627', 'date_created': '2024-02-20T17:27:24.031Z', 'status': 'failed', 'progress': None, 'url': None, 'error': '**The 2008 housing crisis, a look back --v 6.0 --relax --ar 16:9 --no hands, letters, text, words, characters, logos, symbols, sentences** - <@1207808709540053023> (0%) (relaxed)', 'upscaled_urls': None, 'ref': None, 'upscaled': []}}
```

**Comment by xray7474** [comment]
cant you just go into your discord server and type /settings for the midjourney bot, set the method to relax, then prompt like normal ignoring the --relax flag?
I havent tried it since i have a cheap account with no relax time allowed.

**Comment by cboseak** [comment]
When I set it to relax in discord, all requests fail in the API even though
they succeed in discord. I'm guessing there's something about relax mode
that's causing a false positive in the API

**Comment by hgezim** [comment]
Won't fix. It's not hard to do technically, we just don't want to abuse Midjourney and there's timing issues to consider as well (API response).

**Comment by socializemy** [comment]
Does relax mode work on your hosted service?
