### ISSUE TITLE
Bot Not Creating Image on Cloud, but working in local.

### ISSUE THREAD

**Issue by abhizzz** [imagineapi/imagineapi#29]
I have been using imagineapi on local for a while, but now installed it on cloud.

Bot is getting this error , is there any capcha setup needed.

My local machine is working fine. Can anyone help in this.

2024-02-26 16:32:28 debug: Got reponse from 2captcha: 200 {
  "service": "consumer",
  "discord_email": "mailtooyadav@gmail.com",
  "instance": "4abcf11802c4b7562f84688b65dcb894"
}
2024-02-26 16:32:28 debug: Captcha not solved yet. Retrying in 5 seconds... {
  "service": "consumer",
  "discord_email": "mailtooyadav@gmail.com",
  "instance": "4abcf11802c4b7562f84688b65dcb894"
}
2024-02-26 16:32:33 debug: Got reponse from 2captcha: 200 {
  "service": "consumer",
  "discord_email": "mailtooyadav@gmail.com",
  "instance": "4abcf11802c4b7562f84688b65dcb894"
}
2024-02-26 16:32:33 debug: Captcha not solved yet. Retrying in 5 seconds... {
  "service": "consumer",
  "discord_email": "mailtooyadav@gmail.com",
  "instance": "4abcf11802c4b7562f84688b65dcb894"
}
![Bot-8085](https://github.com/imagineapi/imagineapi/assets/42057020/b571e176-934c-4543-ae2d-02ac9b517ef8)

![bot-error-combined](https://github.com/imagineapi/imagineapi/assets/42057020/22615b8e-2db1-40aa-a94a-ccf0a459f92c)

**Comment by hgezim** [comment]
It tries to solve the captcha. Let it. It can take some time. If you see an actual error lmk
