### ISSUE TITLE
Error creating thread2: Not Found

### ISSUE THREAD

**Issue by bigdog765** [imagineapi/imagineapi#34]
I have been generating a bunch of images using a python script that generates 12 images at once. Although, once i reached around 800 images I keep getting this error returned. 
![image](https://github.com/imagineapi/imagineapi/assets/36462380/d1425c98-4d32-4df9-997a-a82924550ca8)
Before this i was getting a similar error: Error creating thread: Too many requests, although I still have a bunch of hours left in my midjourney account. I also tried using a different discord server, but did not work.

**Comment by modernharp** [comment]
Same error,  anew  thread is created but the midjourney command is not actually sent

**Comment by bigdog765** [comment]
Contact them on Telegram, they had to change something manually for me.

**Comment by hgezim** [comment]
This is caused if you deleted the Discord server or channel that you used in settings.
