### ISSUE TITLE
Only  creates threads, not images, started yesterday

### ISSUE THREAD

**Issue by modernharp** [imagineapi/imagineapi#36]
The docker bot is creating a thread but not posting the command.  Here are the logs

2024-05-09 05:19:27 warn: No message found in ws message {
  "service": "consumer",
  "discord_email": "drocsid@liamg.moc",
  "instance": "b07a5625d3c--------a292f65981e8d",
  "rawMessage": {},
  "err": [
    {
      "path": "$input",
      "expected": "(IMessageCreateOrUpdate | IMessageCreateOrUpdateAttached | IMessageCreateOrUpdateWithDescription | IOtherMessageTypes)",
      "value": {
        "t": null,
        "s": null,
        "op": 11,
        "d": null
      }
    }
  ]
}

![image](https://github.com/imagineapi/imagineapi/assets/106825857/91bd4530-68e2-44a8-80d6-0a0b9642a46d)

**Comment by modernharp** [comment]
One of the reasons I haven't got in for your hosted service is because I  am really uncertain about how the support will be like. I see issues not being addressed for more than a month or so.

**Comment by zeeshanghazanfar97** [comment]
I'm facing the same issue, don't think devs are interested in maintaining open source version. The cloud hosted service is way slower and unreliable.

**Comment by modernharp** [comment]
Yeah, the price for the hosted service is attractive but that doesn't matter if it doesn't work.

**Comment by andresbravog** [comment]
Same issue here bot logs show 400 "unknown integration"

```
bot-1  |   },
bot-1  |   "responseStatus": 400,
bot-1  |   "errorDetails": {
bot-1  |     "message": "Integración desconocida",
bot-1  |     "code": 10005
bot-1  |   }
```

**Comment by andresbravog** [comment]
I'm not confident but It might be related to midjourney bot version or command ids changed? 

```
bot-1  |         "id": "938956540159881230",
bot-1  |         "application_id": "936929561302675456",
bot-1  |         "version": "1166847114203123795",
```

I have checked the `application_id` is correct I'm not sure how to check the version or the command

**Comment by modernharp** [comment]
```
      "application_command": {
        "id": "938956540159881230",
        "application_id": "936929561302675456",
        "version": "1166847114203123795",
        "default_member_permissions": null,
        "type": 1,
        "nsfw": false,
        "name": "imagine",
        "description": "Create images with Midjourney",
        "dm_permission": true,
        "contexts": [
          0,
          1,
          2
        ],
        "integration_types": [
          0
        ],
        "options": [
          {
            "type": 3,
            "name": "prompt",
            "description": "The prompt to imagine",
            "required": true
          }
        ]
      },
      "attachments": []
    }
  },
  "responseStatus": 400,
  "errorDetails": {
    "message": "Unknown Integration",
    "code": 10005
  }
}
```

Changed it, still not working

**Comment by modernharp** [comment]
> I'm not confident but It might be related to midjourney bot version or command ids changed?
> 
> ```
> bot-1  |         "id": "938956540159881230",
> bot-1  |         "application_id": "936929561302675456",
> bot-1  |         "version": "1166847114203123795",
> ```
> 
> I have checked the `application_id` is correct I'm not sure how to check the version or the command
> 
> UPDATE:
> 
> seems like the version should be `1237876415471554623`

I made the modification in browser-actions.ts  but still it seems to be getting 1166847114203123795 from somewhere.

**Comment by andresbravog** [comment]
Are you using regular docker compose or the .dev? Regular will need a new docker build version and push. I'll try the change today.

**Comment by modernharp** [comment]
> Are you using regular docker compose or the .dev? Regular will need a new docker build version and push. I'll try the change today.

Using regular Docker compose with build command:

docker compose up -build

Honestly not experienced in Docker.

**Comment by modernharp** [comment]
Okay, perfect. It works after rebuilding the bot image.

**Comment by andresbravog** [comment]
yay! I'll try here and submit the PR. Still waking up ...

**Comment by modernharp** [comment]
> yay! I'll try here and submit the PR. Still waking up ...

Thanks for your help. This is how open source should be :)

**Comment by zeeshanghazanfar97** [comment]
Could you please guide how to implement this fix? I replaced ID on both lines
then clened everything with ```docker system prune --all --force --volumes```
And then docker-compose up --build
But it still doesn't work.

**Comment by andresbravog** [comment]
@zeeshanghazanfar97 

1. Use my branch or replace the value on:

* [here](https://github.com/imagineapi/imagineapi/blob/f13e3ab4908144017e3aa442f3a7fc7fd4bcf364/bot/src/browser-actions.ts#L295)

* [and here](https://github.com/imagineapi/imagineapi/blob/f13e3ab4908144017e3aa442f3a7fc7fd4bcf364/bot/src/browser-actions.ts#L308)

2. Update the docker-compose.yml file replacing the value under `bot:` service:


```
bot:
  image: imagineapi/imagineapi-bot:latest
```

by 

```
bot:
    build: ./bot
```

3. Stop your docker containers

4. Build the bot image

```
docker compose build bot
```

5. Start you docker containers

**Comment by zeeshanghazanfar97** [comment]
@andresbravog You are a life saver. Thank you very much

**Comment by abhizzz** [comment]
Hi @andresbravog 

Thanks for fixing this bug.
I followed the changes you provided and updated the **browser-actions.ts** with correct values and tried to rebuild the Bot container and also update docker.compose.yml with ./bot

However i am getting this error : 
bot-1       | exec ./docker-entrypoint.sh: no such file or directory
bot-1 exited with code 1

Could you please help me with this issue.
Have i missed something.

Thanks in Advance,
Abhishek

**Comment by Ouebflow** [comment]
Hi @andresbravog ,

thanks for all the informations to update.

I followed the steps correctly with the modifications to be made. I've run the “build bot” command but I still have the same problem. The thread is created but no prompt is sent.

I've double-checked the files and the changes are there.

I'm a bit lost :)

**Comment by andresbravog** [comment]
@abhizzz seems like you are missing [this file](https://github.com/imagineapi/imagineapi/blob/main/bot/docker-entrypoint.sh), It might be a good idea to start fresh from `main` branch

**Comment by abhizzz** [comment]
> ike you ar

Thank you. I got it working now.

**Comment by andresbravog** [comment]
Is this project un-maintained? I have not seen any traction on merging the PR and the main branch is clearly not working...

**Comment by hgezim** [comment]
Fixed in https://github.com/imagineapi/imagineapi/pull/39

**Comment by zeeshanghazanfar97** [comment]
Hi @andresbravog, could you please take a look into this issue
https://github.com/imagineapi/imagineapi/issues/53
