### ISSUE TITLE
Status pending for post request, and code forbidden for get request

### ISSUE THREAD

**Issue by ElleeB** [imagineapi/imagineapi#40]
I have been successfully interacting with the api for weeks. As of today, my post request to `/items/images/` never gets beyond `status:pending`, 

and my get request to `/items/images/{image_id}` returns `"{'errors': [{'message': \"You don't have permission to access this.\", 'extensions': {'code': 'FORBIDDEN'}}]}`, even when I hardcode in an existing, successful `image_id`

**Comment by andresbravog** [comment]
check out #36

**Comment by ElleeB** [comment]
Thanks @andresbravog, I'm on a cloud plan :(

**Comment by hgezim** [comment]
@ElleeB I think I handled your request via email since you're on the cloud.
