### ISSUE TITLE
Issue while connecting to api on localserver 

### ISSUE THREAD

**Issue by abhizzz** [imagineapi/imagineapi#8]
Hi,

I have setup imagineapi app on my local docker server, and also i have my Django app through which i am trying to connect the imagine api endpoint,  i have also setup same network on Django app as defined in imagine api docker compose apps.

i am trying to hit endpoint : "http://api:8055/items/images" also tried "http://localhost:8055/items/images" and "http://127.0.0.1:8055/items/images"
However, i am getting below error :

Error :

calling request with payload : {'prompt': 'an image of a boy holding a dog and a cat '}
app-1  | Exception occurred: HTTPConnectionPool(host='api', port=8055): Max retries exceeded with url: /items/images (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa48a7fc9d0>: Failed to establish a new connection: [Errno -3] Try again'))
app-1  | Internal Server Error: /api/user/generate_Image_midjourney
app-1  | [21/Dec/2023 14:39:57] "POST /api/user/generate_Image_midjourney HTTP/1.1" 500 40

However, i am able to generate images using postman and http://localhost:8055/admin/login page successfully.

could you please let me know the issue root cause or what endpoint should i be using from my django app.

**Comment by imagineapi** [comment]
It's a networking issue between your docker containers. Make sure ImagineAPI and your Django app are the in the same docker network.

You can always execute a command inside your django container to see if "api:8055" is resolving.

Definitely a docker networking issue if you can access it from the host machine on port 8055, though.

If you want to use our [cloud plans](https://www.imagineapi.dev/pricing), you just get an endpoint you can hit directly.
