### ISSUE TITLE
Error password authentication failed for user \"postgres\ when running locally

### ISSUE THREAD

**Issue by aryan1107** [imagineapi/imagineapi#9]
Newbie here when I try to run locally it's not creating localhost url I had specified
PUBLIC_URL=http://127.0.0.1:8055

Hoover I found this error from docker
<img width="1028" alt="Screenshot 2023-12-21 at 10 39 37 PM" src="https://github.com/imagineapi/imagineapi/assets/31214277/64d62ee7-2261-45ed-9eaa-ef693a2202b6">

**Comment by imagineapi** [comment]
Try adding quotes around the password fields for the db passwords in `.shared.env`

Then run `docker compose down -v`. Don’t run this command unless you want all your ImagineAPI data deleted.

**Comment by aryan1107** [comment]
Have tried this still doesn't work

**Comment by imagineapi** [comment]
Is `POSTGRES_PASSWORD` and `DB_PASSWORD` the same? Are they both quoted?

**Comment by aryan1107** [comment]
Thanks it worked they were different my bad!
